### ISSUE TITLE
java.lang.NoSuchMethodError: org.jvnet.lafwidget.menu.MenuSearchWidget.showSearchPanels()V

### ISSUE THREAD

**Issue by nleo** [Aries85/LightZone#160]
```
This is LightZone 4.1.3 ()
java.lang.NoSuchMethodError: org.jvnet.lafwidget.menu.MenuSearchWidget.showSearchPanels()V
	at org.jvnet.substance.SubstanceMenuBarUI.showSearchPanels(SubstanceMenuBarUI.java:88)
	at org.jvnet.substance.SubstanceLookAndFeel.initialize(SubstanceLookAndFeel.java:3932)
	at javax.swing.UIManager.setLookAndFeel(UIManager.java:535)
	at org.jvnet.substance.SubstanceLookAndFeel.setSkin(SubstanceLookAndFeel.java:4996)
	at com.lightcrafts.ui.LightZoneSkin.getLightZoneLookAndFeel(LightZoneSkin.java:295)
	at com.lightcrafts.platform.linux.LinuxPlatform.getLookAndFeel(LinuxPlatform.java:57)
	at com.lightcrafts.platform.linux.LinuxLauncher.main(LinuxLauncher.java:36)
```

```
Linux 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17
DISTRIB_CODENAME=qiana
DISTRIB_DESCRIPTION="Linux Mint 17 Qiana"
```

Tryed with openjdk and with oracle:

```
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
```

**Comment by nleo** [comment]
LightZone installed through ppa https://launchpad.net/~otto-kesselgulasch/+archive/ubuntu/lightzone

**Comment by ktgw0316** [comment]
I'm not sure, but
```
sudo apt-get update
sudo apt-get install liblaf-widget-java
sudo apt-get dist-upgrade
sudo apt-get autoremove
```
may work. See http://www.lightzoneproject.org/comment/6495#comment-6495

BTW, the ppa is unofficial and we LightZone dev-team don't support it.

Masahiro
