### ISSUE TITLE
hidpi mode with jre9b125 leads to java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by rndstr** [Aries85/LightZone#181]
I was looking for a hidpi mode and found [this forum thread](http://lightzoneproject.org/lorum/hidpi-mode-linux) that made me aware it should work with jre9.

After installing and running 4.1.6 with jre9b125 it looked great (correct font size) but when I selected a directory to scan it threw exceptions to the console (no crash), nothing else changed. It still said I should select a photo.

I realized `MrPointedHelix` had the same issue which you allegedly fixed I think?

I then compiled it successfully myself with jdk9b125 and when I ran `ant -f linux/build.xml run` it said:

```
run:
     [java] Error occurred during initialization of VM
     [java] java.lang.RuntimeException: Unknown module: java.desktop/sun.print=ALL-UNNAMED
     [java]     at jdk.internal.module.ModuleBootstrap.fail(java.base@9-ea/ModuleBootstrap.java:536)
     [java]     at jdk.internal.module.ModuleBootstrap.addExtraExports(java.base@9-ea/ModuleBootstrap.java:471)
     [java]     at jdk.internal.module.ModuleBootstrap.boot(java.base@9-ea/ModuleBootstrap.java:322)
     [java]     at java.lang.System.initPhase2(java.base@9-ea/System.java:1928)
     [java] 
```

The exception when selecting a folder:

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalAccessError: class com.lightcrafts.jai.opimage.LCMSColorConvertOpImage (in unnamed module @0x5442a311) cannot access class sun
.awt.image.ByteInterleavedRaster (in module java.desktop) because module java.desktop does not export sun.awt.image to unnamed module @0x5442a311
        at com.lightcrafts.jai.opimage.LCMSColorConvertOpImage.computeRect(LCMSColorConvertOpImage.java:95)
        at com.lightcrafts.mediax.jai.PointOpImage.computeTile(PointOpImage.java:857)
        at com.lightcrafts.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:899)
        at com.lightcrafts.mediax.jai.OpImage.getTile(OpImage.java:1125)
        at com.lightcrafts.mediax.jai.RenderedOp.getTile(RenderedOp.java:2252)
        at com.lightcrafts.jai.utils.Functions$sRGBWrapper.getTile(Functions.java:459)
        at com.lightcrafts.mediax.jai.PlanarImage.getData(PlanarImage.java:2085)
        at com.lightcrafts.mediax.jai.PlanarImage.getExtendedData(PlanarImage.java:2508)
        at com.lightcrafts.mediax.jai.ScaleOpImage.computeTile(ScaleOpImage.java:1253)
        at com.lightcrafts.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:899)
        at com.lightcrafts.mediax.jai.OpImage.getTile(OpImage.java:1125)
        at com.lightcrafts.mediax.jai.PlanarImage.cobbleByte(PlanarImage.java:2918)
        at com.lightcrafts.mediax.jai.PlanarImage.getData(PlanarImage.java:2169)
        at com.lightcrafts.mediax.jai.RenderedOp.getData(RenderedOp.java:2271)
        at sun.java2d.SunGraphics2D.drawRenderedImage(java.desktop@9-ea/SunGraphics2D.java:2719)
        at com.lightcrafts.ui.editor.DisabledImageComponent.paintComponent(DisabledImageComponent.java:68)
        at javax.swing.JComponent.paint(java.desktop@9-ea/JComponent.java:1055)
        at javax.swing.JComponent.paintChildren(java.desktop@9-ea/JComponent.java:888)
        at com.lightcrafts.ui.editor.DisabledImages.paintChildren(DisabledImages.java:70)
        at javax.swing.JComponent.paint(java.desktop@9-ea/JComponent.java:1064)
        at javax.swing.JComponent.paintChildren(java.desktop@9-ea/JComponent.java:888)
        at javax.swing.JComponent.paint(java.desktop@9-ea/JComponent.java:1064)
        at javax.swing.JLayeredPane.paint(java.desktop@9-ea/JLayeredPane.java:589)
        at javax.swing.JComponent.paintChildren(java.desktop@9-ea/JComponent.java:888)
        at javax.swing.JSplitPane.paintChildren(java.desktop@9-ea/JSplitPane.java:1024)
        at javax.swing.JComponent.paint(java.desktop@9-ea/JComponent.java:1064)
        at javax.swing.JComponent.paintToOffscreen(java.desktop@9-ea/JComponent.java:5227)
        at javax.swing.BufferStrategyPaintManager.paint(java.desktop@9-ea/BufferStrategyPaintManager.java:246)
        at javax.swing.RepaintManager.paint(java.desktop@9-ea/RepaintManager.java:1302)
        at javax.swing.JComponent._paintImmediately(java.desktop@9-ea/JComponent.java:5175)
        at javax.swing.JComponent.paintImmediately(java.desktop@9-ea/JComponent.java:4986)
        at javax.swing.RepaintManager$4.run(java.desktop@9-ea/RepaintManager.java:846)
        at javax.swing.RepaintManager$4.run(java.desktop@9-ea/RepaintManager.java:829)
        at java.security.AccessController.doPrivileged(java.base@9-ea/Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@9-ea/ProtectionDomain.java:77)
        at javax.swing.RepaintManager.paintDirtyRegions(java.desktop@9-ea/RepaintManager.java:829)
        at javax.swing.RepaintManager.paintDirtyRegions(java.desktop@9-ea/RepaintManager.java:804)
        at javax.swing.RepaintManager.prePaintDirtyRegions(java.desktop@9-ea/RepaintManager.java:753)
        at javax.swing.RepaintManager.access$1200(java.desktop@9-ea/RepaintManager.java:65)
        at javax.swing.RepaintManager$ProcessingRunnable.run(java.desktop@9-ea/RepaintManager.java:1762)
        at java.awt.event.InvocationEvent.dispatch(java.desktop@9-ea/InvocationEvent.java:313)
        at java.awt.EventQueue.dispatchEventImpl(java.desktop@9-ea/EventQueue.java:759)
        at java.awt.EventQueue.access$500(java.desktop@9-ea/EventQueue.java:97)
        at java.awt.EventQueue$3.run(java.desktop@9-ea/EventQueue.java:712)
        at java.awt.EventQueue$3.run(java.desktop@9-ea/EventQueue.java:706)
        at java.security.AccessController.doPrivileged(java.base@9-ea/Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@9-ea/ProtectionDomain.java:77)
        at java.awt.EventQueue.dispatchEvent(java.desktop@9-ea/EventQueue.java:729)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@9-ea/EventDispatchThread.java:199)
        at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@9-ea/EventDispatchThread.java:124)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@9-ea/EventDispatchThread.java:113)
        at java.awt.EventDispatchThread.pumpEvents(java.desktop@9-ea/EventDispatchThread.java:109)
        at java.awt.EventDispatchThread.pumpEvents(java.desktop@9-ea/EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.run(java.desktop@9-ea/EventDispatchThread.java:90)
```

http://openjdk.java.net/jeps/260

**Comment by ktgw0316** [comment]
I think that this issue fixed in v4.1.6. Could you check it again with the latest source?
