### ISSUE TITLE
Linux: OpenJDK update (10.0.2+13-1ubuntu0.18.04.1) breaks lightzone

### ISSUE THREAD

**Issue by digibirdtrek** [Aries85/LightZone#232]
After update to OpenJDK (10.0.2+13-1ubuntu0.18.04.1), lightzone fails to launch with the following errors.
--------------------------------------------

Starting LightZone version 4.1.8 ...
with options :
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.1)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.1, mixed mode)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.lightcrafts.platform.Launcher (file:/usr/share/java/lightzone/lightcrafts.jar) to method sun.swing.SwingUtilities2.isLocalDisplay()
WARNING: Please consider reporting this to the maintainers of com.lightcrafts.platform.Launcher
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
This is LightZone 4.1.8 ()
Running Java version 10.0.2 (amd64)
java.lang.Error: no ComponentUI class for: com.lightcrafts.app.ExceptionDialog[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,icon=,initialValue=,message=JOptionPane message,messageType=PLAIN_MESSAGE,optionType=DEFAULT_OPTION,wantsInput=false]
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:760)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:133)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:790)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1065)
	at java.desktop/javax.swing.JOptionPane.updateUI(JOptionPane.java:1873)
	at java.desktop/javax.swing.JOptionPane.<init>(JOptionPane.java:1838)
	at java.desktop/javax.swing.JOptionPane.<init>(JOptionPane.java:1801)
	at java.desktop/javax.swing.JOptionPane.<init>(JOptionPane.java:1769)
	at java.desktop/javax.swing.JOptionPane.<init>(JOptionPane.java:1747)
	at java.desktop/javax.swing.JOptionPane.<init>(JOptionPane.java:1727)
	at java.desktop/javax.swing.JOptionPane.<init>(JOptionPane.java:1711)
	at java.desktop/javax.swing.JOptionPane.<init>(JOptionPane.java:1699)
	at com.lightcrafts.app.ExceptionDialog.<init>(ExceptionDialog.java:40)
	at com.lightcrafts.platform.Launcher.init(Launcher.java:47)
	at com.lightcrafts.platform.linux.LinuxLauncher.main(LinuxLauncher.java:11)
java.lang.Error: no ComponentUI class for: javax.swing.JTextArea[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,caretColor=,disabledTextColor=,editable=true,margin=,selectedTextColor=,selectionColor=,colums=0,columWidth=0,rows=0,rowHeight=0,word=false,wrap=false]
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:760)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:133)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:790)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1065)
	at java.desktop/javax.swing.text.JTextComponent.updateUI(JTextComponent.java:352)
	at java.desktop/javax.swing.text.JTextComponent.<init>(JTextComponent.java:326)
	at java.desktop/javax.swing.JTextArea.<init>(JTextArea.java:199)
	at java.desktop/javax.swing.JTextArea.<init>(JTextArea.java:135)
	at com.lightcrafts.app.ExceptionDialog.<init>(ExceptionDialog.java:42)
	at com.lightcrafts.platform.Launcher.init(Launcher.java:47)
	at com.lightcrafts.platform.linux.LinuxLauncher.main(LinuxLauncher.java:11)
java.lang.Error: no ComponentUI class for: javax.swing.JTextArea[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,caretColor=,disabledTextColor=,editable=true,margin=,selectedTextColor=,selectionColor=,colums=0,columWidth=0,rows=0,rowHeight=0,word=false,wrap=false]
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:760)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:133)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:790)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1065)
	at java.desktop/javax.swing.text.JTextComponent.updateUI(JTextComponent.java:352)
	at java.desktop/javax.swing.text.JTextComponent.<init>(JTextComponent.java:326)
	at java.desktop/javax.swing.JTextArea.<init>(JTextArea.java:199)
	at java.desktop/javax.swing.JTextArea.<init>(JTextArea.java:135)
	at com.lightcrafts.app.ExceptionDialog.<init>(ExceptionDialog.java:50)
	at com.lightcrafts.platform.Launcher.init(Launcher.java:47)
	at com.lightcrafts.platform.linux.LinuxLauncher.main(LinuxLauncher.java:11)
java.lang.Error: no ComponentUI class for: javax.swing.JButton[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=null,paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=false,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=Show Details,defaultCapable=true]
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:760)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:133)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:790)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1065)
	at java.desktop/javax.swing.JButton.updateUI(JButton.java:141)
	at java.desktop/javax.swing.AbstractButton.init(AbstractButton.java:2136)
	at java.desktop/javax.swing.JButton.<init>(JButton.java:131)
	at java.desktop/javax.swing.JButton.<init>(JButton.java:104)
	at com.lightcrafts.app.ExceptionDialog.<init>(ExceptionDialog.java:60)
	at com.lightcrafts.platform.Launcher.init(Launcher.java:47)
	at com.lightcrafts.platform.linux.LinuxLauncher.main(LinuxLauncher.java:11)
java.lang.Error: no ComponentUI class for: javax.swing.JViewport[,0,0,0x0,invalid,layout=javax.swing.ViewportLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777224,maximumSize=,minimumSize=,preferredSize=,isViewSizeSet=false,lastPaintPosition=,scrollUnderway=false]
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:760)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:133)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:790)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1065)
	at java.desktop/javax.swing.JViewport.updateUI(JViewport.java:328)
	at java.desktop/javax.swing.JViewport.<init>(JViewport.java:291)
	at java.desktop/javax.swing.JScrollPane.createViewport(JScrollPane.java:905)
	at java.desktop/javax.swing.JScrollPane.<init>(JScrollPane.java:299)
	at java.desktop/javax.swing.JScrollPane.<init>(JScrollPane.java:324)
	at com.lightcrafts.app.ExceptionDialog.<init>(ExceptionDialog.java:61)
	at com.lightcrafts.platform.Launcher.init(Launcher.java:47)
	at com.lightcrafts.platform.linux.LinuxLauncher.main(LinuxLauncher.java:11)
java.lang.Error: no ComponentUI class for: javax.swing.JScrollPane$ScrollBar[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=4194304,maximumSize=,minimumSize=,preferredSize=,blockIncrement=10,orientation=VERTICAL,unitIncrement=1]
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:760)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:133)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:790)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1065)
	at java.desktop/javax.swing.JScrollBar.updateUI(JScrollBar.java:231)
	at java.desktop/javax.swing.JScrollBar.<init>(JScrollBar.java:165)
	at java.desktop/javax.swing.JScrollBar.<init>(JScrollBar.java:182)
	at java.desktop/javax.swing.JScrollPane$ScrollBar.<init>(JScrollPane.java:702)
	at java.desktop/javax.swing.JScrollPane.createVerticalScrollBar(JScrollPane.java:854)
	at java.desktop/javax.swing.JScrollPane.<init>(JScrollPane.java:300)
	at java.desktop/javax.swing.JScrollPane.<init>(JScrollPane.java:324)
	at com.lightcrafts.app.ExceptionDialog.<init>(ExceptionDialog.java:61)
	at com.lightcrafts.platform.Launcher.init(Launcher.java:47)
	at com.lightcrafts.platform.linux.LinuxLauncher.main(LinuxLauncher.java:11)
java.lang.Error: no ComponentUI class for: javax.swing.JScrollPane$ScrollBar[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=4194304,maximumSize=,minimumSize=,preferredSize=,blockIncrement=10,orientation=HORIZONTAL,unitIncrement=1]
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:760)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:133)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:790)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1065)
	at java.desktop/javax.swing.JScrollBar.updateUI(JScrollBar.java:231)
	at java.desktop/javax.swing.JScrollBar.<init>(JScrollBar.java:165)
	at java.desktop/javax.swing.JScrollBar.<init>(JScrollBar.java:182)
	at java.desktop/javax.swing.JScrollPane$ScrollBar.<init>(JScrollPane.java:702)
	at java.desktop/javax.swing.JScrollPane.createHorizontalScrollBar(JScrollPane.java:798)
	at java.desktop/javax.swing.JScrollPane.<init>(JScrollPane.java:301)
	at java.desktop/javax.swing.JScrollPane.<init>(JScrollPane.java:324)
	at com.lightcrafts.app.ExceptionDialog.<init>(ExceptionDialog.java:61)
	at com.lightcrafts.platform.Launcher.init(Launcher.java:47)
	at com.lightcrafts.platform.linux.LinuxLauncher.main(LinuxLauncher.java:11)
java.lang.Error: no ComponentUI class for: javax.swing.JScrollPane[,0,0,0x0,invalid,layout=javax.swing.ScrollPaneLayout$UIResource,alignmentX=0.0,alignmentY=0.0,border=,flags=8,maximumSize=,minimumSize=,preferredSize=,columnHeader=,horizontalScrollBar=javax.swing.JScrollPane$ScrollBar[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=4194304,maximumSize=,minimumSize=,preferredSize=,blockIncrement=10,orientation=HORIZONTAL,unitIncrement=1],horizontalScrollBarPolicy=HORIZONTAL_SCROLLBAR_AS_NEEDED,lowerLeft=,lowerRight=,rowHeader=,upperLeft=,upperRight=,verticalScrollBar=javax.swing.JScrollPane$ScrollBar[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=4194304,maximumSize=,minimumSize=,preferredSize=,blockIncrement=10,orientation=VERTICAL,unitIncrement=1],verticalScrollBarPolicy=VERTICAL_SCROLLBAR_AS_NEEDED,viewport=javax.swing.JViewport[,0,0,0x0,invalid,layout=javax.swing.ViewportLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=25165832,maximumSize=,minimumSize=,preferredSize=,isViewSizeSet=false,lastPaintPosition=,scrollUnderway=false],viewportBorder=]
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:760)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:133)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:790)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1065)
	at java.desktop/javax.swing.JScrollPane.updateUI(JScrollPane.java:391)
	at java.desktop/javax.swing.JScrollPane.<init>(JScrollPane.java:306)
	at java.desktop/javax.swing.JScrollPane.<init>(JScrollPane.java:324)
	at com.lightcrafts.app.ExceptionDialog.<init>(ExceptionDialog.java:61)
	at com.lightcrafts.platform.Launcher.init(Launcher.java:47)
	at com.lightcrafts.platform.linux.LinuxLauncher.main(LinuxLauncher.java:11)
java.lang.Error: no ComponentUI class for: javax.swing.JRadioButton[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=null,paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=false,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=<html>Save all files and exit  <b>(Recommended)</b></html>]
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:760)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:133)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:790)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1065)
	at java.desktop/javax.swing.JRadioButton.updateUI(JRadioButton.java:191)
	at java.desktop/javax.swing.AbstractButton.init(AbstractButton.java:2136)
	at java.desktop/javax.swing.JToggleButton.<init>(JToggleButton.java:177)
	at java.desktop/javax.swing.JRadioButton.<init>(JRadioButton.java:179)
	at java.desktop/javax.swing.JRadioButton.<init>(JRadioButton.java:143)
	at com.lightcrafts.app.ExceptionDialog.<init>(ExceptionDialog.java:63)
	at com.lightcrafts.platform.Launcher.init(Launcher.java:47)
	at com.lightcrafts.platform.linux.LinuxLauncher.main(LinuxLauncher.java:11)
java.lang.Error: no ComponentUI class for: javax.swing.JRadioButton[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=null,paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=false,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=<html>Continue  (The program may now be unstable)</html>]
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:760)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:133)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:790)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1065)
	at java.desktop/javax.swing.JRadioButton.updateUI(JRadioButton.java:191)
	at java.desktop/javax.swing.AbstractButton.init(AbstractButton.java:2136)
	at java.desktop/javax.swing.JToggleButton.<init>(JToggleButton.java:177)
	at java.desktop/javax.swing.JRadioButton.<init>(JRadioButton.java:179)
	at java.desktop/javax.swing.JRadioButton.<init>(JRadioButton.java:143)
	at com.lightcrafts.app.ExceptionDialog.<init>(ExceptionDialog.java:64)
	at com.lightcrafts.platform.Launcher.init(Launcher.java:47)
	at com.lightcrafts.platform.linux.LinuxLauncher.main(LinuxLauncher.java:11)
java.lang.Error: no ComponentUI class for: javax.swing.JRadioButton[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=null,paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=false,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=<html>Exit without saving files</html>]
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:760)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:133)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:790)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1065)
	at java.desktop/javax.swing.JRadioButton.updateUI(JRadioButton.java:191)
	at java.desktop/javax.swing.AbstractButton.init(AbstractButton.java:2136)
	at java.desktop/javax.swing.JToggleButton.<init>(JToggleButton.java:177)
	at java.desktop/javax.swing.JRadioButton.<init>(JRadioButton.java:179)
	at java.desktop/javax.swing.JRadioButton.<init>(JRadioButton.java:143)
	at com.lightcrafts.app.ExceptionDialog.<init>(ExceptionDialog.java:65)
	at com.lightcrafts.platform.Launcher.init(Launcher.java:47)
	at com.lightcrafts.platform.linux.LinuxLauncher.main(LinuxLauncher.java:11)
java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.desktop/java.awt.Toolkit.newAWTError(Toolkit.java:472)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:488)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1608)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:532)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:613)
	at java.desktop/sun.swing.SwingUtilities2.getSystemMnemonicKeyMask(SwingUtilities2.java:2143)
	at java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.initComponentDefaults(BasicLookAndFeel.java:1096)
	at java.desktop/javax.swing.plaf.metal.MetalLookAndFeel.initComponentDefaults(MetalLookAndFeel.java:440)
	at java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:150)
	at java.desktop/javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(MetalLookAndFeel.java:1560)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:587)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:628)
	at java.desktop/javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1403)
	at java.desktop/javax.swing.UIManager.initialize(UIManager.java:1516)
	at java.desktop/javax.swing.UIManager.maybeInitialize(UIManager.java:1482)
	at java.desktop/javax.swing.UIManager.getLookAndFeel(UIManager.java:495)
	at org.jvnet.substance.SubstanceLookAndFeel.setSkin(SubstanceLookAndFeel.java:4995)
	at com.lightcrafts.ui.LightZoneSkin.getLightZoneLookAndFeel(LightZoneSkin.java:295)
	at com.lightcrafts.platform.linux.LinuxPlatform.getLookAndFeel(LinuxPlatform.java:82)
	at com.lightcrafts.platform.Launcher.init(Launcher.java:33)
	at com.lightcrafts.platform.linux.LinuxLauncher.main(LinuxLauncher.java:11)
Caused by: java.lang.ClassNotFoundException: org.GNOME.Accessibility.AtkWrapper
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:485)
	... 27 more
Exception in thread "main" java.lang.NullPointerException
	at java.desktop/javax.swing.text.JTextComponent.setCaretPosition(JTextComponent.java:1691)
	at com.lightcrafts.app.ExceptionDialog.showError(ExceptionDialog.java:138)
	at com.lightcrafts.app.ExceptionDialog.handle(ExceptionDialog.java:103)
	at com.lightcrafts.platform.Launcher.init(Launcher.java:47)
	at com.lightcrafts.platform.linux.LinuxLauncher.main(LinuxLauncher.java:11)

**Comment by juhavlintula** [comment]
I experienced yesterday the same. I was successfully running the latest patches on Java-10, but yesterday it stopped to work. The only thing that has changed was the latest Ubuntu updates, but I didn't look what components were updated.

I was able to run Lightzone with command `ant -f linux/build.xml run` when I set the Java environment variable to point to Java-8.

**Comment by juhavlintula** [comment]
Tested the second option (editing `/etc/java-11-openjdk/accessibility.properties`) and works fine.

**Comment by ktgw0316** [comment]
Seems to be fixed in 10.0.2+13-1ubuntu0.18.04.2.
