### ISSUE TITLE
Both the Master and 4.1.9 fails to build on macOS Catalina 10.15.3

### ISSUE THREAD

**Issue by NordicFlyer** [Aries85/LightZone#246]
I appears that the link [](http://repo2.maven.org/maven2/org/apache/ivy/ivy/2.4.0/ivy-2.4.0.jar)
 is dead.

`bruce@Unobtanium macosx % ant build
Buildfile: /Users/bruce/Projects/LightZone-4.1.9/macosx/build.xml

common:

download-ivy:
      [get] Getting: http://repo2.maven.org/maven2/org/apache/ivy/ivy/2.4.0/ivy-2.4.0.jar
      [get] To: /Users/bruce/Projects/LightZone-4.1.9/lightcrafts/lib/ivy.jar
      [get] Error getting http://repo2.maven.org/maven2/org/apache/ivy/ivy/2.4.0/ivy-2.4.0.jar to /Users/bruce/Projects/LightZone-4.1.9/lightcrafts/lib/ivy.jar

BUILD FAILED
/Users/bruce/Projects/LightZone-4.1.9/macosx/build.xml:31: The following error occurred while executing this line:
/Users/bruce/Projects/LightZone-4.1.9/lightcrafts/build.xml:57: java.net.UnknownHostException: repo2.maven.org
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.Socket.connect(Socket.java:603)
	at java.base/java.net.Socket.connect(Socket.java:552)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1248)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
	at org.apache.tools.ant.taskdefs.Get$GetThread.openConnection(Get.java:766)
	at org.apache.tools.ant.taskdefs.Get$GetThread.get(Get.java:676)
	at org.apache.tools.ant.taskdefs.Get$GetThread.run(Get.java:666)`

**Comment by ktgw0316** [comment]
d7b6f24 fixed this issue.
